import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'es' | 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    home: 'Inicio',
    catalog: 'Catálogo',
    wishlist: 'Lista de Deseos',
    cart: 'Carrito',
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    logout: 'Cerrar Sesión',
    dashboard: 'Panel',
    search: 'Buscar libros...',
    language: 'Idioma',
    account: 'Cuenta',
    settings: 'Ajustes',
    myAccount: 'Mi Cuenta',
    adminPanel: 'Panel Admin',
    aboutUs: 'Sobre Nosotros',
    location: 'Ubicación',
    viewAllCatalog: 'Ver Todo el Catálogo',
    adminSettings: 'Ajustes Admin',
    searchPlaceholder: 'Buscar libros, autores, editoriales, ISBN...',
    theme: 'Tema',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    autoMode: 'Automático',
    searching: 'Buscando...',
    viewAllResults: 'Ver todos los resultados',
    noResults: 'No se encontraron resultados',
    hello: 'Hola',
    light: 'Claro',
    dark: 'Oscuro',
    auto: 'Auto',

    heroTitle: 'Descubre tu próxima',
    heroHighlight: 'gran lectura',
    heroSubtitle: 'Miles de libros esperándote. Desde clásicos atemporales hasta las últimas novedades. Encuentra historias que transformarán tu mundo.',
    exploreCatalog: 'Explorar Catálogo',
    viewFeatured: 'Ver Destacados',
    featuredBooks: 'Libros Destacados',
    latestReleases: 'Últimas Novedades',
    specialOffers: 'Ofertas Especiales',
    viewAll: 'Ver todos',
    viewAllReleases: 'Ver todas',
    viewOffers: 'Ver ofertas',
    noOffersTitle: 'No hay ofertas activas por el momento',
    noOffersDesc: 'Estamos seleccionando las mejores promociones para ti. Mientras tanto, explora nuestra colección completa.',
    newToLibrary: '¿Nuevo en nuestra librería?',
    joinCommunity: 'Únete a nuestra comunidad de lectores y disfruta de beneficios exclusivos, descuentos especiales y recomendaciones personalizadas.',
    registerFree: 'Registrarse Gratis',
    cantFindBook: '¿No encuentras el libro que buscas?',
    contactUsHelper: 'Contáctanos y haremos todo lo posible por conseguirlo para ti.',
    contactBtn: 'Contactar Ahora',

    loginTitle: 'Iniciar Sesión',
    loginSubtitle: 'Accede a tu cuenta para continuar con tu experiencia de lectura',
    email: 'Email',
    emailOrUsername: 'Email o Usuario',
    emailOrUsernamePlaceholder: 'tu@email.com o usuario',
    password: 'Contraseña',
    loggingIn: 'Iniciando...',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes cuenta?',
    registerHere: 'Regístrate aquí',
    incorrectCredentials: 'Email o contraseña incorrectos',
    hidePassword: 'Ocultar contraseña',
    showPassword: 'Mostrar contraseña',

    registerTitle: 'Crear Cuenta',
    registerSubtitle: 'Únete a nuestra comunidad de lectores',
    fullName: 'Nombre Completo',
    confirmPassword: 'Confirmar Contraseña',
    creating: 'Creando...',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    loginHere: 'Inicia sesión aquí',
    passwordsDontMatch: 'Las contraseñas no coinciden',

    footerDescription: 'Tu librería de confianza con la mejor selección de libros en español y otros idiomas. Descubre nuevas historias y encuentra tus próximas lecturas favoritas.',
    quickLinks: 'Enlaces Rápidos',
    categories: 'Categorías',
    contact: 'Contacto',
    allRightsReserved: 'Todos los derechos reservados',
    privacyPolicy: 'Política de Privacidad',
    termsOfService: 'Términos de Servicio',
    cookies: 'Cookies',

    addToCart: 'Añadir al Carrito',
    addToWishlist: 'Añadir a Lista de Deseos',
    removeFromWishlist: 'Eliminar de Lista de Deseos',
    buyNow: 'Comprar Ahora',
    outOfStock: 'Agotado',
    inStock: 'Disponible',
    available: 'disponibles',
    available_singular: 'disponible',
    price: 'Precio',
    author: 'Autor',
    description: 'Descripción',
    details: 'Detalles',

    emptyCart: 'Tu carrito está vacío',
    emptyCartMessage: 'Parece que no has añadido ningún libro a tu carrito todavía.',
    startShopping: 'Comenzar a comprar',
    cartTotal: 'Total del Carrito',
    subtotal: 'Subtotal',
    shipping: 'Envío',
    total: 'Total',
    proceedCheckout: 'Proceder al Pago',
    continueShopping: 'Continuar Comprando',

    emptyWishlist: 'Tu lista de deseos está vacía',
    emptyWishlistMessage: 'Guarda tus libros favoritos aquí para más tarde.',
    moveToCart: 'Mover al Carrito',
    remove: 'Eliminar',
    new: 'NUEVO',
    sale: 'OFERTA',

    // UserDashboard
    overview: 'Resumen',
    myReservations: 'Mis Reservas',
    notifications: 'Notificaciones',
    myOrders: 'Mis Pedidos',
    myProfile: 'Mi Perfil',
    totalOrders: 'Total de Pedidos',
    activeReservations: 'Reservas Activas',
    unreadNotifications: 'Sin Leer',
    edit: 'Editar',
    save: 'Guardar',
    cancel: 'Cancelar',
    username: 'Usuario',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    memberSince: 'Miembro desde',
    name: 'Nombre',
    phone: 'Teléfono',
    address: 'Dirección',
    city: 'Ciudad',
    postalCode: 'Código Postal',
    manageReservations: 'Gestiona tus reservas de libros',
    all: 'Todas',
    pending: 'Pendientes',
    confirmed: 'Confirmadas',
    delivered: 'Entregadas',
    noReservations: 'No tienes reservas',
    inStatus: 'en estado',
    cancelReservation: 'Cancelar Reserva',
    pickupBefore: 'Recoger antes del',
    year: 'Año',
    publisher: 'Editorial',
    notSpecified: 'No especificado',
    notSpecifiedFemale: 'No especificada',
    accountInfo: 'Información de tu cuenta',
    welcome: 'Bienvenido',
    orderHistory: 'Historial de Pedidos',
    reviewPreviousOrders: 'Revisa tus pedidos anteriores',
    loadingOrders: 'Cargando pedidos...',
    noOrders: 'No tienes pedidos realizados',
    viewDetails: 'Ver Detalles',
    orderDetails: 'Detalles del Pedido',
    shippingAddress: 'Dirección de Envío',
    addressNotAvailable: 'Dirección no disponible',
    paymentMethod: 'Método de Pago',
    close: 'Cerrar',
    quantity: 'Cantidad',
    loadingNotifications: 'Cargando notificaciones...',
    unread: 'sin leer',
    markAllAsRead: 'Marcar todas como leídas',
    noNotifications: 'No tienes notificaciones',
    newOrder: 'Nuevo Pedido',
    orderPlaced: 'Pedido Realizado',
    newOrderMessage: 'Nuevo pedido #{0} recibido de {1}',
    orderPlacedMessage: 'Tu pedido #{0} se ha creado correctamente y está en estado: {1}.',
    orderStatusPending: 'pendiente',
    orderNumber: 'Número de Pedido',
    date: 'Fecha',
    status: 'Estado',
    statusPending: 'Pendiente',
    statusProcessing: 'Procesando',
    statusShipped: 'Enviado',
    statusDelivered: 'Entregado',
    statusCancelled: 'Cancelado',
    actions: 'Acciones',
    
    // Check out flow new keys
    requestOrder: 'Solicitar Pedido',
    validatingCart: 'Validando...',
    proceedToCheckout: 'Ir a Caja',
    verifyingStock: 'Verificando Stock',
    verifyStockMessage: 'Tu pedido ha sido recibido. Verificaremos el stock y te notificaremos en 24-48h.' ,
    pendingVerification: 'Pendiente de Verificación',
    paymentPending: 'Pendiente de Pago',
    payNow: 'Pagar Ahora',

    // Order Confirmation Page
    orderReceived: '¡Pedido Recibido!',
    orderReceivedSubtitle: 'Hemos recibido tu solicitud correctamente.',
    nextSteps: '¿Qué sucede ahora?',
    verificationStep: 'Verificación de Stock',
    verificationDesc: 'En las próximas 24-48 horas, verificaremos que los libros estén en perfecto estado en nuestro almacén.',
    paymentStep: 'Confirmación y Pago',
    paymentDesc: 'Te enviaremos un email cuando estemos listos. Podrás acceder a tu cuenta y completar el pago.',
    shippingStep: 'Envío',
    shippingDesc: 'Una vez pagado, prepararemos y enviaremos tu paquete inmediatamente.',
    goToMyOrders: 'Ir a Mis Pedidos',
    // About Page
    aboutUsTitle: 'Sobre Nosotros',
    aboutUsSubtitle: 'Más de 100 años difundiendo cultura y pasión por la lectura',
    ourHistory: 'Nuestra Historia',
    ourHistoryP1: 'Fundada en 1920 en el corazón de Madrid, la Librería Pérez Galdós comenzó como un pequeño rincón para los amantes de la literatura clásica. Nombrada en honor al ilustre escritor canario que tan bien retrató nuestra ciudad, nos hemos mantenido fieles a su espíritu de observación y amor por las letras.',
    ourHistoryP2: 'A lo largo de las décadas, hemos sido testigos de la historia de nuestra ciudad, sirviendo de refugio para escritores, estudiantes y lectores curiosos. Lo que empezó con unas pocas estanterías es hoy un referente cultural que combina la tradición del librero de oficio con las nuevas tecnologías.',
    ourMission: 'Nuestra Misión',
    ourMissionText: 'Creemos que un libro no es solo papel y tinta, sino una puerta a otros mundos. Nuestra misión es conectar a cada lector con su próxima gran historia, ofreciendo un catálogo curado con mimo que abarca desde las últimas novedades hasta joyas descatalogadas.',
    ourValues: 'Nuestros Valores',
    valueProximity: 'Cercanía',
    valueProximityText: 'Trato personalizado y asesoramiento experto para cada lector.',
    valueQuality: 'Calidad',
    valueQualityText: 'Selección rigurosa de títulos y ediciones cuidadas.',
    valueCommitment: 'Compromiso',
    valueCommitmentText: 'Fomento de la lectura y apoyo a autores locales.',
    
    // Location Page
    ourStores: 'Nuestras Librerías',
    twoUniqueSpaces: 'Dos espacios únicos en el centro de Madrid',
    heartOfOurHistory: 'El corazón de nuestra historia',
    ourNewAdventure: 'Nuestra nueva aventura literaria',
    viewOnGoogleMaps: 'Ver en Google Maps',
    addressLabel: 'Dirección',
    scheduleLabel: 'Horario',
    contactLabel: 'Contacto',
    mondayToFriday: 'Lunes a Viernes',
    saturdays: 'Sábados',
    sundays: 'Domingos',
    checkOpening: 'Consultar apertura',
    closed: 'Cerrado',
    
    // Contact Page
    contactTitle: 'Contacto',
    contactSubtitle: 'Estamos aquí para ayudarte. Escríbenos.',
    sendUsMessage: 'Envíanos un mensaje',
    contactDescription: 'Si tienes alguna duda sobre un libro, un pedido o simplemente quieres saludarnos, completa el formulario y te responderemos lo antes posible.',
    emailLabel: 'Correo Electrónico',
    phonesLabel: 'Teléfonos',
    addressesLabel: 'Direcciones',
    fullNameLabel: 'Nombre Completo',
    yourName: 'Tu nombre',
    yourEmail: 'tu@email.com',
    subjectLabel: 'Asunto',
    queryReason: 'Motivo de la consulta',
    messageLabel: 'Mensaje',
    writeYourMessage: 'Escribe aquí tu mensaje...',
    sendMessage: 'Enviar Mensaje',
    messageSent: '¡Mensaje Enviado!',
    thankYouMessage: 'Gracias por contactarnos. Te responderemos en breve.',
    sendAnotherMessage: 'Enviar otro mensaje',
    
    // Cart Page
    yourCartIsEmpty: 'Tu carrito está vacío',
    discoverOurSelection: '¡Descubre nuestra increíble selección de libros y añade algunos a tu carrito!',
    exploreCatalogBtn: 'Explorar Catálogo',
    shoppingCart: 'Carrito de Compras',
    emptyCartBtn: 'Vaciar carrito',
    byAuthor: 'por',
    removeFromCart: 'Eliminar del carrito',
    orderSummary: 'Resumen del Pedido',
    subtotalLabel: 'Subtotal',
    bookSingular: 'libro',
    bookPlural: 'libros',
    shippingMethodLabel: 'Método de Envío',
    standardShipping: 'Envío Estándar',
    expressShipping: 'Envío Express',
    standardOption: 'Estándar',
    expressOption: 'Express',
    freeLabel: 'Gratis',
    freeFromAmount: 'Gratis desde',
    shippingCostLabel: 'Coste Envío',
    taxesLabel: 'Impuestos',
    estimatedTotalLabel: 'Total Estimado',
    addMoreForFreeShipping: 'Añade {0} más para envío estándar gratuito',
    loginToCompletePurchase: 'Inicia sesión para completar tu compra',
    securePayment: 'Compra 100% segura',
    fastShipping: 'Envío en 24-48h',
    freeReturns: 'Devolución gratis',
    calculatedAtCheckout: 'Se calculará al finalizar',
    continue: 'Continuar al Pago',
    
    // Checkout Form
    personalInformation: 'Información Personal',
    firstName: 'Nombre',
    lastName: 'Apellidos',
    firstNamePlaceholder: 'Tu nombre',
    lastNamePlaceholder: 'Tus apellidos',
    phonePlaceholder: '600123456',
    shippingAndAddress: 'Dirección y Envío',
    workingDays: 'días laborables',
    streetAddress: 'Dirección',
    streetAddressPlaceholder: 'Calle, número, piso, puerta...',
    cityPlaceholder: 'Madrid',
    postalCodeLabel: 'Código Postal',
    postalCodePlaceholder: '28001',
    province: 'Provincia',
    provincePlaceholder: 'Madrid',
    country: 'País',
    countryPlaceholder: 'España',
    saveAsDefaultAddress: 'Guardar esta información como predeterminada en mi perfil',
    notesOptional: 'Observaciones (Opcional)',
    notesPlaceholder: 'Notas adicionales sobre tu pedido (horarios de entrega, instrucciones especiales, etc.)',
    checkoutTotal: 'Total',
    backToCart: 'Volver al Carrito',
    confirmOrder: 'Confirmar Pedido',
    processingOrder: 'Procesando...',
    
    // Stripe Checkout
    preparingPayment: 'Preparando el pago...',
    errorProcessingPayment: 'Error al Procesar el Pago',
    configurationError: 'Error de Configuración',
    couldNotLoadPaymentSystem: 'No se pudo cargar el sistema de pagos. Por favor, contacta con soporte.',
    backButton: 'Volver',
    finalizePayment: 'Finalizar Pago',
    iva: 'IVA',
    
    // Stripe Payment Form
    paymentInformation: 'Información de Pago',
    totalToPay: 'Total a pagar',
    errorProcessingPaymentGeneric: 'Error al procesar el pago',
    unknownError: 'Error desconocido',
    processingPayment: 'Procesando...',
    payAmount: 'Pagar',
    securePaymentByStripe: 'Pago seguro procesado por Stripe',
    pleaseWaitDoNotClose: 'Por favor, espere. No cierre ni recargue esta página mientras procesamos su pago.',
  },
  en: {
    home: 'Home',
    catalog: 'Catalog',
    wishlist: 'Wishlist',
    cart: 'Cart',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    dashboard: 'Dashboard',
    search: 'Search books...',
    language: 'Language',
    account: 'Account',
    settings: 'Settings',
    myAccount: 'My Account',
    adminPanel: 'Admin Panel',
    aboutUs: 'About Us',
    location: 'Location',
    viewAllCatalog: 'View All Catalog',
    adminSettings: 'Admin Settings',
    searchPlaceholder: 'Search books, authors, publishers, ISBN...',
    theme: 'Theme',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    autoMode: 'Automatic',
    searching: 'Searching...',
    viewAllResults: 'View all results',
    noResults: 'No results found',
    hello: 'Hello',
    light: 'Light',
    dark: 'Dark',
    auto: 'Auto',

    heroTitle: 'Discover your next',
    heroHighlight: 'great read',
    heroSubtitle: 'Thousands of books waiting for you. From timeless classics to the latest releases. Find stories that will transform your world.',
    exploreCatalog: 'Explore Catalog',
    viewFeatured: 'View Featured',
    featuredBooks: 'Featured Books',
    latestReleases: 'Latest Releases',
    specialOffers: 'Special Offers',
    viewAll: 'View all',
    viewAllReleases: 'View all',
    viewOffers: 'View offers',
    noOffersTitle: 'No active offers at the moment',
    noOffersDesc: 'We are selecting the best promotions for you. In the meantime, explore our full collection.',
    newToLibrary: 'New to our bookstore?',
    joinCommunity: 'Join our community of readers and enjoy exclusive benefits, special discounts and personalized recommendations.',
    registerFree: 'Register Free',
    cantFindBook: "Can't find the book you're looking for?",
    contactUsHelper: "Contact us and we'll do our best to get it for you.",
    contactBtn: 'Contact Now',

    loginTitle: 'Login',
    loginSubtitle: 'Access your account to continue your reading experience',
    email: 'Email',
    emailOrUsername: 'Email or Username',
    emailOrUsernamePlaceholder: 'your@email.com or username',
    password: 'Password',
    loggingIn: 'Logging in...',
    forgotPassword: 'Forgot your password?',
    noAccount: 'Don\'t have an account?',
    registerHere: 'Register here',
    incorrectCredentials: 'Incorrect email or password',
    hidePassword: 'Hide password',
    showPassword: 'Show password',

    registerTitle: 'Create Account',
    registerSubtitle: 'Join our community of readers',
    fullName: 'Full Name',
    confirmPassword: 'Confirm Password',
    creating: 'Creating...',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    passwordsDontMatch: 'Passwords don\'t match',

    footerDescription: 'Your trusted bookstore with the best selection of books in Spanish and other languages. Discover new stories and find your next favorite reads.',
    quickLinks: 'Quick Links',
    categories: 'Categories',
    contact: 'Contact',
    allRightsReserved: 'All rights reserved',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    cookies: 'Cookies',

    addToCart: 'Add to Cart',
    addToWishlist: 'Add to Wishlist',
    removeFromWishlist: 'Remove from Wishlist',
    buyNow: 'Buy Now',
    outOfStock: 'Out of Stock',
    inStock: 'In Stock',
    available: 'available',
    available_singular: 'available',
    price: 'Price',
    author: 'Author',
    description: 'Description',
    details: 'Details',

    emptyCart: 'Your cart is empty',
    emptyCartMessage: 'Looks like you haven\'t added any books to your cart yet.',
    startShopping: 'Start Shopping',
    cartTotal: 'Cart Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    proceedCheckout: 'Proceed to Checkout',
    continueShopping: 'Continue Shopping',

    emptyWishlist: 'Your wishlist is empty',
    emptyWishlistMessage: 'Save your favorite books here for later.',
    moveToCart: 'Move to Cart',
    remove: 'Remove',
    new: 'NEW',
    sale: 'SALE',

    // UserDashboard
    overview: 'Overview',
    myReservations: 'My Reservations',
    notifications: 'Notifications',
    myOrders: 'My Orders',
    myProfile: 'My Profile',
    totalOrders: 'Total Orders',
    activeReservations: 'Active Reservations',
    unreadNotifications: 'Unread',
    edit: 'Edit',
    save: 'Save',
    cancel: 'Cancel',
    username: 'Username',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    memberSince: 'Member since',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    city: 'City',
    postalCode: 'Postal Code',
    manageReservations: 'Manage your book reservations',
    all: 'All',
    pending: 'Pending',
    confirmed: 'Confirmed',
    delivered: 'Delivered',
    noReservations: 'You have no reservations',
    inStatus: 'in status',
    cancelReservation: 'Cancel Reservation',
    pickupBefore: 'Pick up before',
    year: 'Year',
    publisher: 'Publisher',
    notSpecified: 'Not specified',
    notSpecifiedFemale: 'Not specified',
    accountInfo: 'Your account information',
    welcome: 'Welcome',
    orderHistory: 'Order History',
    reviewPreviousOrders: 'Review your previous orders',
    loadingOrders: 'Loading orders...',
    noOrders: 'You have no orders',
    viewDetails: 'View Details',
    orderDetails: 'Order Details',
    shippingAddress: 'Shipping Address',
    addressNotAvailable: 'Address not available',
    paymentMethod: 'Payment Method',
    close: 'Close',
    quantity: 'Quantity',
    loadingNotifications: 'Loading notifications...',
    unread: 'unread',
    markAllAsRead: 'Mark all as read',
    noNotifications: 'You have no notifications',
    newOrder: 'New Order',
    orderPlaced: 'Order Placed',
    newOrderMessage: 'New order #{0} received from {1}',
    orderPlacedMessage: 'Your order #{0} has been created successfully and is in status: {1}.',
    orderStatusPending: 'pending',
    orderNumber: 'Order Number',
    date: 'Date',
    status: 'Status',
    statusPending: 'Pending',
    statusProcessing: 'Processing',
    statusShipped: 'Shipped',
    statusDelivered: 'Delivered',
    statusCancelled: 'Cancelled',
    actions: 'Actions',
    
    // About Page
    aboutUsTitle: 'About Us',
    aboutUsSubtitle: 'Over 100 years spreading culture and passion for reading',
    ourHistory: 'Our History',
    ourHistoryP1: 'Founded in 1920 in the heart of Madrid, Librería Pérez Galdós began as a small corner for lovers of classic literature. Named in honor of the illustrious Canarian writer who so well portrayed our city, we have remained faithful to his spirit of observation and love for letters.',
    ourHistoryP2: 'Throughout the decades, we have witnessed the history of our city, serving as a refuge for writers, students, and curious readers. What started with a few shelves is today a cultural reference that combines the tradition of the professional bookseller with new technologies.',
    ourMission: 'Our Mission',
    ourMissionText: 'We believe that a book is not just paper and ink, but a door to other worlds. Our mission is to connect each reader with their next great story, offering a carefully curated catalog that ranges from the latest releases to out-of-print gems.',
    ourValues: 'Our Values',
    valueProximity: 'Closeness',
    valueProximityText: 'Personalized service and expert advice for each reader.',
    valueQuality: 'Quality',
    valueQualityText: 'Rigorous selection of titles and carefully chosen editions.',
    valueCommitment: 'Commitment',
    valueCommitmentText: 'Promoting reading and supporting local authors.',
    
    // Location Page
    ourStores: 'Our Bookstores',
    twoUniqueSpaces: 'Two unique spaces in the center of Madrid',
    heartOfOurHistory: 'The heart of our history',
    ourNewAdventure: 'Our new literary adventure',
    viewOnGoogleMaps: 'View on Google Maps',
    addressLabel: 'Address',
    scheduleLabel: 'Schedule',
    contactLabel: 'Contact',
    mondayToFriday: 'Monday to Friday',
    saturdays: 'Saturdays',
    sundays: 'Sundays',
    checkOpening: 'Check opening',
    closed: 'Closed',
    
    // Contact Page
    contactTitle: 'Contact',
    contactSubtitle: 'We are here to help you. Write to us.',
    sendUsMessage: 'Send us a message',
    contactDescription: 'If you have any questions about a book, an order, or just want to say hello, fill out the form and we will respond as soon as possible.',
    emailLabel: 'Email',
    phonesLabel: 'Phones',
    addressesLabel: 'Addresses',
    fullNameLabel: 'Full Name',
    yourName: 'Your name',
    yourEmail: 'your@email.com',
    subjectLabel: 'Subject',
    queryReason: 'Reason for inquiry',
    messageLabel: 'Message',
    writeYourMessage: 'Write your message here...',
    sendMessage: 'Send Message',
    messageSent: 'Message Sent!',
    thankYouMessage: 'Thank you for contacting us. We will respond shortly.',
    sendAnotherMessage: 'Send another message',
    
    // Cart Page
    yourCartIsEmpty: 'Your cart is empty',
    discoverOurSelection: 'Discover our incredible selection of books and add some to your cart!',
    exploreCatalogBtn: 'Explore Catalog',
    shoppingCart: 'Shopping Cart',
    emptyCartBtn: 'Empty cart',
    byAuthor: 'by',
    removeFromCart: 'Remove from cart',
    orderSummary: 'Order Summary',
    subtotalLabel: 'Subtotal',
    bookSingular: 'book',
    bookPlural: 'books',
    shippingMethodLabel: 'Shipping Method',
    standardShipping: 'Standard Shipping',
    expressShipping: 'Express Shipping',
    standardOption: 'Standard',
    expressOption: 'Express',
    freeLabel: 'Free',
    freeFromAmount: 'Free from',
    shippingCostLabel: 'Shipping Cost',
    taxesLabel: 'Taxes',
    estimatedTotalLabel: 'Estimated Total',
    addMoreForFreeShipping: 'Add {0} more for free standard shipping',
    loginToCompletePurchase: 'Log in to complete your purchase',
    securePayment: '100% secure payment',
    fastShipping: 'Shipping in 24-48h',
    freeReturns: 'Free returns',
    calculatedAtCheckout: 'Calculated at checkout',
    continue: 'Continue to Payment',
    
    // Checkout Form
    personalInformation: 'Personal Information',
    firstName: 'First Name',
    lastName: 'Last Name',
    firstNamePlaceholder: 'Your first name',
    lastNamePlaceholder: 'Your last name',
    phonePlaceholder: '600123456',
    shippingAndAddress: 'Shipping & Address',
    workingDays: 'working days',
    streetAddress: 'Street Address',
    streetAddressPlaceholder: 'Street, number, floor, door...',
    cityPlaceholder: 'Madrid',
    postalCodeLabel: 'Postal Code',
    postalCodePlaceholder: '28001',
    province: 'Province',
    provincePlaceholder: 'Madrid',
    country: 'Country',
    countryPlaceholder: 'Spain',
    saveAsDefaultAddress: 'Save this information as default in my profile',
    notesOptional: 'Notes (Optional)',
    notesPlaceholder: 'Additional notes about your order (delivery times, special instructions, etc.)',
    checkoutTotal: 'Total',
    backToCart: 'Back to Cart',
    confirmOrder: 'Confirm Order',
    processingOrder: 'Processing...',
    
    // Stripe Checkout
    preparingPayment: 'Preparing payment...',
    errorProcessingPayment: 'Error Processing Payment',
    configurationError: 'Configuration Error',
    couldNotLoadPaymentSystem: 'Could not load payment system. Please contact support.',
    backButton: 'Back',
    finalizePayment: 'Finalize Payment',
    iva: 'VAT',
    
    // Stripe Payment Form
    paymentInformation: 'Payment Information',
    totalToPay: 'Total to pay',
    errorProcessingPaymentGeneric: 'Error processing payment',
    unknownError: 'Unknown error',
    processingPayment: 'Processing...',
    payAmount: 'Pay',
    securePaymentByStripe: 'Secure payment processed by Stripe',
    pleaseWaitDoNotClose: 'Please wait. Do not close or reload this page while we process your payment.',
    
    // Order Confirmation Page
    orderReceived: 'Order Received!',
    orderReceivedSubtitle: 'We have successfully received your request.',
    nextSteps: 'What happens now?',
    verificationStep: 'Stock Verification',
    verificationDesc: 'In the next 24-48 hours, we will verify that the books are in perfect condition in our warehouse.',
    paymentStep: 'Confirmation & Payment',
    paymentDesc: 'We will send you an email when we are ready. You can then access your account and complete the payment.',
    shippingStep: 'Shipping',
    shippingDesc: 'Once paid, we will prepare and ship your package immediately.',
    goToMyOrders: 'Go to My Orders',
  },
  fr: {
    home: 'Accueil',
    catalog: 'Catalogue',
    wishlist: 'Liste de Souhaits',
    cart: 'Panier',
    login: 'Connexion',
    register: 'S\'inscrire',
    logout: 'Déconnexion',
    dashboard: 'Tableau de Bord',
    search: 'Rechercher des livres...',
    language: 'Langue',
    account: 'Compte',
    settings: 'Paramètres',
    myAccount: 'Mon Compte',
    adminPanel: 'Panneau Admin',
    aboutUs: 'À Propos',
    location: 'Emplacement',
    viewAllCatalog: 'Voir Tout le Catalogue',
    adminSettings: 'Paramètres Admin',
    searchPlaceholder: 'Rechercher livres, auteurs, éditeurs, ISBN...',
    theme: 'Thème',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    autoMode: 'Automatique',
    searching: 'Recherche...',
    viewAllResults: 'Voir tous les résultats',
    noResults: 'Aucun résultat trouvé',
    hello: 'Bonjour',
    light: 'Clair',
    dark: 'Sombre',
    auto: 'Auto',

    heroTitle: 'Découvrez votre prochaine',
    heroHighlight: 'grande lecture',
    heroSubtitle: 'Des milliers de livres vous attendent. Des classiques intemporels aux dernières nouveautés. Trouvez des histoires qui transformeront votre monde.',
    exploreCatalog: 'Explorer le Catalogue',
    viewFeatured: 'Voir les Vedettes',
    featuredBooks: 'Livres en Vedette',
    latestReleases: 'Dernières Nouveautés',
    specialOffers: 'Offres Spéciales',
    viewAll: 'Voir tout',
    viewAllReleases: 'Voir toutes',
    viewOffers: 'Voir les offres',
    noOffersTitle: 'Pas d\'offres actives pour le moment',
    noOffersDesc: 'Nous sélectionnons les meilleures promotions pour vous. En attendant, explorez notre collection complète.',
    newToLibrary: 'Nouveau dans notre librairie?',
    joinCommunity: 'Rejoignez notre communauté de lecteurs et profitez d\'avantages exclusifs, de réductions spéciales et de recommandations personnalisées.',
    registerFree: 'S\'inscrire Gratuitement',
    cantFindBook: 'Vous ne trouvez pas le livre que vous cherchez ?',
    contactUsHelper: 'Contactez-nous et nous ferons de notre mieux pour l\'obtenir pour vous.',
    contactBtn: 'Contacter Maintenant',

    loginTitle: 'Connexion',
    loginSubtitle: 'Accédez à votre compte pour continuer votre expérience de lecture',
    email: 'Email',
    emailOrUsername: 'Email ou Nom d\'utilisateur',
    emailOrUsernamePlaceholder: 'votre@email.com ou nom d\'utilisateur',
    password: 'Mot de passe',
    loggingIn: 'Connexion...',
    forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Vous n\'avez pas de compte?',
    registerHere: 'Inscrivez-vous ici',
    incorrectCredentials: 'Email ou mot de passe incorrect',
    hidePassword: 'Masquer le mot de passe',
    showPassword: 'Afficher le mot de passe',

    registerTitle: 'Créer un Compte',
    registerSubtitle: 'Rejoignez notre communauté de lecteurs',
    fullName: 'Nom Complet',
    confirmPassword: 'Confirmer le Mot de Passe',
    creating: 'Création...',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    loginHere: 'Connectez-vous ici',
    passwordsDontMatch: 'Les mots de passe ne correspondent pas',

    footerDescription: 'Votre librairie de confiance avec la meilleure sélection de livres en espagnol et autres langues. Découvrez de nouvelles histoires et trouvez vos prochaines lectures préférées.',
    quickLinks: 'Liens Rapides',
    categories: 'Catégories',
    contact: 'Contact',
    allRightsReserved: 'Tous droits réservés',
    privacyPolicy: 'Politique de Confidentialité',
    termsOfService: 'Conditions d\'Utilisation',
    cookies: 'Cookies',

    addToCart: 'Ajouter au Panier',
    addToWishlist: 'Ajouter à la Liste',
    removeFromWishlist: 'Retirer de la Liste',
    buyNow: 'Acheter Maintenant',
    outOfStock: 'Épuisé',
    inStock: 'Disponible',
    available: 'disponibles',
    available_singular: 'disponible',
    price: 'Prix',
    author: 'Auteur',
    description: 'Description',
    details: 'Détails',

    emptyCart: 'Votre panier est vide',
    emptyCartMessage: 'Il semble que vous n\'ayez pas encore ajouté de livres à votre panier.',
    startShopping: 'Commencer vos Achats',
    cartTotal: 'Total du Panier',
    subtotal: 'Sous-total',
    shipping: 'Livraison',
    total: 'Total',
    proceedCheckout: 'Procéder au Paiement',
    continueShopping: 'Continuer les Achats',

    emptyWishlist: 'Votre liste est vide',
    emptyWishlistMessage: 'Enregistrez vos livres préférés ici pour plus tard.',
    moveToCart: 'Déplacer au Panier',
    remove: 'Supprimer',
    new: 'NOUVEAU',
    sale: 'OFFRE',

    // UserDashboard
    overview: 'Aperçu',
    myReservations: 'Mes Réservations',
    notifications: 'Notifications',
    myOrders: 'Mes Commandes',
    myProfile: 'Mon Profil',
    totalOrders: 'Total des Commandes',
    activeReservations: 'Réservations Actives',
    unreadNotifications: 'Non Lues',
    edit: 'Modifier',
    save: 'Enregistrer',
    cancel: 'Annuler',
    username: 'Nom d\'utilisateur',
    currentPassword: 'Mot de Passe Actuel',
    newPassword: 'Nouveau Mot de Passe',
    memberSince: 'Membre depuis',
    name: 'Nom',
    phone: 'Téléphone',
    address: 'Adresse',
    city: 'Ville',
    postalCode: 'Code Postal',
    manageReservations: 'Gérez vos réservations de livres',
    all: 'Toutes',
    pending: 'En Attente',
    confirmed: 'Confirmées',
    delivered: 'Livrées',
    noReservations: 'Vous n\'avez aucune réservation',
    inStatus: 'en statut',
    cancelReservation: 'Annuler la Réservation',
    pickupBefore: 'Retirer avant le',
    year: 'Année',
    publisher: 'Éditeur',
    notSpecified: 'Non spécifié',
    notSpecifiedFemale: 'Non spécifiée',
    accountInfo: 'Informations de votre compte',
    welcome: 'Bienvenue',
    orderHistory: 'Historique des Commandes',
    reviewPreviousOrders: 'Consultez vos commandes précédentes',
    loadingOrders: 'Chargement des commandes...',
    noOrders: 'Vous n\'avez aucune commande',
    viewDetails: 'Voir les Détails',
    orderDetails: 'Détails de la Commande',
    shippingAddress: 'Adresse de Livraison',
    addressNotAvailable: 'Adresse non disponible',
    paymentMethod: 'Méthode de Paiement',
    close: 'Fermer',
    quantity: 'Quantité',
    loadingNotifications: 'Chargement des notifications...',
    unread: 'non lues',
    markAllAsRead: 'Tout marquer comme lu',
    noNotifications: 'Vous n\'avez aucune notification',
    newOrder: 'Nouvelle Commande',
    orderPlaced: 'Commande Passée',
    newOrderMessage: 'Nouvelle commande #{0} reçue de {1}',
    orderPlacedMessage: 'Votre commande #{0} a été créée avec succès et est en statut: {1}.',
    orderStatusPending: 'en attente',
    orderNumber: 'Numéro de Commande',
    date: 'Date',
    status: 'Statut',
    statusPending: 'En Attente',
    
    // Order Confirmation Page
    orderReceived: 'Commande Reçue !',
    orderReceivedSubtitle: 'Nous avons bien reçu votre demande.',
    nextSteps: 'Que se passe-t-il maintenant ?',
    verificationStep: 'Vérification du Stock',
    verificationDesc: 'Dans les prochaines 24-48 heures, nous vérifierons que les livres sont en parfait état dans notre entrepôt.',
    paymentStep: 'Confirmation et Paiement',
    paymentDesc: 'Nous vous enverrons un email lorsque nous serons prêts. Vous pourrez alors accéder à votre compte et effectuer le paiement.',
    shippingStep: 'Expédition',
    shippingDesc: 'Une fois payé, nous préparerons et expédierons votre colis immédiatement.',
    goToMyOrders: 'Aller à Mes Commandes',
    statusProcessing: 'En Traitement',
    statusShipped: 'Expédié',
    statusDelivered: 'Livré',
    statusCancelled: 'Annulé',
    actions: 'Actions',
    
    // About Page
    aboutUsTitle: 'À Propos de Nous',
    aboutUsSubtitle: 'Plus de 100 ans à diffuser la culture et la passion de la lecture',
    ourHistory: 'Notre Histoire',
    ourHistoryP1: 'Fondée en 1920 au cœur de Madrid, la Librairie Pérez Galdós a commencé comme un petit coin pour les amateurs de littérature classique. Nommée en l\'honneur de l\'illustre écrivain canarien qui a si bien dépeint notre ville, nous sommes restés fidèles à son esprit d\'observation et d\'amour des lettres.',
    ourHistoryP2: 'Au fil des décennies, nous avons été témoins de l\'histoire de notre ville, servant de refuge aux écrivains, étudiants et lecteurs curieux. Ce qui a commencé avec quelques étagères est aujourd\'hui une référence culturelle qui combine la tradition du libraire professionnel avec les nouvelles technologies.',
    ourMission: 'Notre Mission',
    ourMissionText: 'Nous croyons qu\'un livre n\'est pas seulement du papier et de l\'encre, mais une porte vers d\'autres mondes. Notre mission est de connecter chaque lecteur avec sa prochaine grande histoire, en offrant un catalogue soigneusement sélectionné qui va des dernières nouveautés aux joyaux épuisés.',
    ourValues: 'Nos Valeurs',
    valueProximity: 'Proximité',
    valueProximityText: 'Service personnalisé et conseil expert pour chaque lecteur.',
    valueQuality: 'Qualité',
    valueQualityText: 'Sélection rigoureuse de titres et éditions soignées.',
    valueCommitment: 'Engagement',
    valueCommitmentText: 'Promotion de la lecture et soutien aux auteurs locaux.',
    
    // Location Page
    ourStores: 'Nos Librairies',
    twoUniqueSpaces: 'Deux espaces uniques au centre de Madrid',
    heartOfOurHistory: 'Le cœur de notre histoire',
    ourNewAdventure: 'Notre nouvelle aventure littéraire',
    viewOnGoogleMaps: 'Voir sur Google Maps',
    addressLabel: 'Adresse',
    scheduleLabel: 'Horaires',
    contactLabel: 'Contact',
    mondayToFriday: 'Lundi au Vendredi',
    saturdays: 'Samedis',
    sundays: 'Dimanches',
    checkOpening: 'Consulter l\'ouverture',
    closed: 'Fermé',
    
    // Contact Page
    contactTitle: 'Contact',
    contactSubtitle: 'Nous sommes là pour vous aider. Écrivez-nous.',
    sendUsMessage: 'Envoyez-nous un message',
    contactDescription: 'Si vous avez des questions sur un livre, une commande ou si vous voulez simplement nous saluer, remplissez le formulaire et nous vous répondrons dans les plus brefs délais.',
    emailLabel: 'Email',
    phonesLabel: 'Téléphones',
    addressesLabel: 'Adresses',
    fullNameLabel: 'Nom Complet',
    yourName: 'Votre nom',
    yourEmail: 'votre@email.com',
    subjectLabel: 'Sujet',
    queryReason: 'Motif de la demande',
    messageLabel: 'Message',
    writeYourMessage: 'Écrivez votre message ici...',
    sendMessage: 'Envoyer le Message',
    messageSent: 'Message Envoyé!',
    thankYouMessage: 'Merci de nous avoir contactés. Nous vous répondrons bientôt.',
    sendAnotherMessage: 'Envoyer un autre message',
    
    // Cart Page
    yourCartIsEmpty: 'Votre panier est vide',
    discoverOurSelection: 'Découvrez notre incroyable sélection de livres et ajoutez-en à votre panier!',
    exploreCatalogBtn: 'Explorer le Catalogue',
    shoppingCart: 'Panier d\'Achats',
    emptyCartBtn: 'Vider le panier',
    byAuthor: 'par',
    removeFromCart: 'Retirer du panier',
    orderSummary: 'Résumé de la Commande',
    subtotalLabel: 'Sous-total',
    bookSingular: 'livre',
    bookPlural: 'livres',
    shippingMethodLabel: 'Méthode d\'Expédition',
    standardShipping: 'Expédition Standard',
    expressShipping: 'Expédition Express',
    standardOption: 'Standard',
    expressOption: 'Express',
    freeLabel: 'Gratuit',
    freeFromAmount: 'Gratuit à partir de',
    shippingCostLabel: 'Frais d\'Expédition',
    taxesLabel: 'Taxes',
    estimatedTotalLabel: 'Total Estimé',
    addMoreForFreeShipping: 'Ajoutez {0} de plus pour la livraison standard gratuite',
    loginToCompletePurchase: 'Connectez-vous pour finaliser votre achat',
    securePayment: 'Paiement 100% sécurisé',
    fastShipping: 'Expédition en 24-48h',
    freeReturns: 'Retours gratuits',
    calculatedAtCheckout: 'Calculé au moment du paiement',
    continue: 'Continuer vers le paiement',
    
    // Checkout Form
    personalInformation: 'Informations Personnelles',
    firstName: 'Prénom',
    lastName: 'Nom de Famille',
    firstNamePlaceholder: 'Votre prénom',
    lastNamePlaceholder: 'Votre nom de famille',
    phonePlaceholder: '600123456',
    shippingAndAddress: 'Livraison et Adresse',
    workingDays: 'jours ouvrables',
    streetAddress: 'Adresse',
    streetAddressPlaceholder: 'Rue, numéro, étage, porte...',
    cityPlaceholder: 'Madrid',
    postalCodeLabel: 'Code Postal',
    postalCodePlaceholder: '28001',
    province: 'Province',
    provincePlaceholder: 'Madrid',
    country: 'Pays',
    countryPlaceholder: 'Espagne',
    saveAsDefaultAddress: 'Enregistrer ces informations par défaut dans mon profil',
    notesOptional: 'Notes (Optionnel)',
    notesPlaceholder: 'Notes supplémentaires sur votre commande (horaires de livraison, instructions spéciales, etc.)',
    checkoutTotal: 'Total',
    backToCart: 'Retour au Panier',
    confirmOrder: 'Confirmer la Commande',
    processingOrder: 'Traitement...',
    
    // Stripe Checkout
    preparingPayment: 'Préparation du paiement...',
    errorProcessingPayment: 'Erreur de Traitement du Paiement',
    configurationError: 'Erreur de Configuration',
    couldNotLoadPaymentSystem: 'Impossible de charger le système de paiement. Veuillez contacter le support.',
    backButton: 'Retour',
    finalizePayment: 'Finaliser le Paiement',
    iva: 'TVA',
    
    // Stripe Payment Form
    paymentInformation: 'Informations de Paiement',
    totalToPay: 'Total à payer',
    errorProcessingPaymentGeneric: 'Erreur lors du traitement du paiement',
    unknownError: 'Erreur inconnue',
    processingPayment: 'Traitement...',
    payAmount: 'Payer',
    securePaymentByStripe: 'Paiement sécurisé traité par Stripe',
    pleaseWaitDoNotClose: 'Veuillez patienter. Ne fermez pas et ne rechargez pas cette page pendant le traitement de votre paiement.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
